<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_filters"
 *
 * Auto generated by SAV Library Kickstarter 15-02-23
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Filters',
    'description' => 'A set of filters (alphabetic, months, search, selectors, mini calendar...) to be used with extension created by SAV Library Kickstarter for the SAV Library Plus and SAV Library Mvc.',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '11.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.28-11.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
